build:
	gxc -cc-options "-I/opt/homebrew/Cellar/raptor/2.0.16/include/raptor2" -ld-options "-L/opt/homebrew/Cellar/raptor/2.0.16/lib -lraptor2" ffi.ss
	gxc -cc-options "-I/opt/homebrew/Cellar/raptor/2.0.16/include/raptor2" -ld-options "-L/opt/homebrew/Cellar/raptor/2.0.16/lib -lraptor2" -exe -o test test.ss