;; File: test_webscrape.ss
(import "webscrape")
(import :std/format)

(def (run-tests)
  (let ((uri "https://markwatson.com"))
    (displayln "=============================================")
    (displayln "1. TESTING PLAIN TEXT EXTRACTION FROM: " uri)
    (displayln "=============================================")
    (let ((text (get-plain-text uri)))
      (displayln (substring text 0 (min (string-length text) 600)))
      (displayln "\n... [truncated] ...\n"))

    (displayln "=============================================")
    (displayln "2. TESTING MARKDOWN EXTRACTION FROM: " uri)
    (displayln "=============================================")
    (let ((md (get-markdown uri)))
      (displayln (substring md 0 (min (string-length md) 600)))
      (displayln "\n... [truncated] ...\n"))

    (displayln "=============================================")
    (displayln "3. TESTING HEADERS EXTRACTION (H1, H2, H3) FROM: " uri)
    (displayln "=============================================")
    (let ((headers (get-headers uri)))
      (for-each (lambda (h)
                  (let ((level (car h))
                        (text (cadr h)))
                    (displayln (make-string level #\#) " " text)))
                headers)
      (displayln ""))

    (displayln "=============================================")
    (displayln "4. TESTING LINKS EXTRACTION FROM: " uri)
    (displayln "=============================================")
    (let ((links (get-links uri)))
      (displayln "Found " (length links) " links. Printing the first 15:")
      (let loop ((count 0) (lst links))
        (when (and (< count 15) (not (null? lst)))
          (let* ((link (car lst))
                 (url (car link))
                 (text (cadr link)))
            (displayln (format "  ~a. [~a] -> ~a" (+ count 1) text url))
            (loop (+ count 1) (cdr lst)))))
      (displayln ""))))

(run-tests)
