(print "\n***** Loading SchemeKBS System\n\n")

(load "data/stop-words.scm")
(print "utils.scm:\n")
(load "utils.scm")
(load "generated-code/lexdata.scm")
(print "fasttag.scm:\n")
(load "fasttag.scm")
(print "category.scm:\n")
(load "category.scm")
(load "levenshtein.scm")
(print "Load category data:\n")
;;(load-cat-dat)
(load "generated-code/cat-data-tables.scm") ; generated by Ruby utilities
(load "proper-names.scm")
(load-name-data)
;; (load-place-data)  ;; TBD: convert this code to read place data files; create place data files !!!
(load "summarize.scm")
;; database support:
;;(load "sqlite/sqlite.o1")
(load "key-phrases.scm")
(load "main.scm")


